driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: win2012r2
    driver_config:
      box: opentable/win-2012r2-standard-amd64-nocm
  - name: win2008r2
    driver_config:
      box: opentable/win-2008r2-standard-amd64-nocm

suites:
  - name: default
    run_list:
      - recipe[iis::default]
