Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'test/integration/**/*'

Style/GuardClause:
  Exclude:
    - 'libraries/helper.rb'

Style/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'test/integration/**/*'

# Fix missing Carriage return error on Windows
# https://github.com/bbatsov/rubocop/issues/4293
Layout/EndOfLine:
  EnforcedStyle: lf
