# rubocop todo

Lint/ParenthesesAsGroupedExpression:
  Exclude:
    - 'test/**/*.rb'

Naming/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'test/integration/**/*'

Style/IfUnlessModifier:
  Exclude:
    - 'resources/pool.rb'
    - 'resources/site.rb'
